### ISSUE TITLE
Module is not working anymore

### ISSUE THREAD

**Issue by robbinonline** [PtrBld/MMM-Scrobbler#5]
Any idea why? Try it on different setups

**Comment by asifma** [comment]
Same here, not working for me either anymore =/. Loved to have it back..

**Comment by PtrBld** [comment]
Ok I wil look into it soon

**Comment by asifma** [comment]
Thanks :)! Just tell me if you need any additional information from me..

**Comment by asifma** [comment]
Sometime it shows up, I change song, and it disappears again directly.

**Comment by asifma** [comment]
Did you come up with any solution :)?

**Comment by PtrBld** [comment]
The module is working for me. Can you please post your logs here?

**Comment by asifma** [comment]
What type of log do you need? Ive done: npm start dev 
But cant find anything wrong? The problem is that the delay is very long. Even if i set to 3 seconds. It takes around 80 seconds for the new song to show up..Most of the times not at all..
But it disappears as soon as i change song. That part is working..

**Comment by PtrBld** [comment]
This is due to the delay with Last.FM. I think I can boost performance a bit but are currently quite busy. I will look into if I find time.

**Comment by asifma** [comment]
I see, would be great if possible :)!
Thanks for the awesome module..

**Comment by cd360** [comment]
I second this. Exact same issues as @asifma  from the sounds of it. Works for the first track, then disappears permanently.

**Comment by mucpi** [comment]
I have the same issue. But only if i play with spotify connect on raspberry pi. If I play from computer or phone it works fine.

**Comment by cd360** [comment]
The first song I play on my pc or phone scrobbler fine, but then that's it. It stops regardless of platform

**Comment by teknohe** [comment]
Works for a few songs then abruptly stops working.  This is one of my favorite modules, It's a shame it's been abandoned as this is likely an easy fix.

**Comment by ghost** [comment]
Doesnt work with me either

**Comment by ghost** [comment]
Ok, I found the issue

Last.fm's API, from what I see on r/last.fm is pretty much broken

It's and issue with the API itself not the module

**Comment by TimerWolf** [comment]
For me it always work if i restart MagicMirror or the reload the modules, so if the module itself would reload it self after every track in some way it would be a working workaround i think as it can without any problem detect the first and the next track....

And if no track is played for a while, instead of read the API every minute or whatever the settings is, reload it instead of try check the API...

**Comment by TimerWolf** [comment]
- An work around for this that works for me would be to modify the "MMM-Scrobbler.js"

Change

```javascript
      if (!(i.status >= 200 && i.status < 400)) {
        Log.error(r.message);
        self.hide(1000);
      }
```

to

```javascript
      if (!(i.status >= 200 && i.status < 400)) {
        Log.error(r.message);
        self.hide(1000);
        self.updateDom();
      }
```

**Comment by teknohe** [comment]
I will try it!  Thank-you!

**Comment by PtrBld** [comment]
I "fixed" this with your work around and a new config option. Hope this works now for everyone.
