### ISSUE TITLE
Scrobble data...

### ISSUE THREAD

**Issue by loganslightning** [PtrBld/MMM-Scrobbler#7]
Every time I load Magic Mirror the scrobbler module shows "Scrobble data..." for a second and disappears. After that nothing happens. Any ideas of what to do here?

**Comment by PtrBld** [comment]
Are you playing any music on spotify? The module hides when no song is playing. Furthermore have you connected your spotify account with LAST.FM since I am using their API?

**Comment by loganslightning** [comment]
So yeah I've checked to make sure I was playing music and that I've correctly connected spotify to my LAST.FM account. When I go to my LAST.FM home page it shows what I am currently playing, but it still fails to show up on the mirror. Could it have anything to do with the position I have set it to? I believe it is set to "top_bar"?

**Comment by loganslightning** [comment]
Could it also have something to do with the api key authentication? @PtrBld http://www.last.fm/api/desktopauth

**Comment by ganget** [comment]
@loganslightning You're not using the [desktop authorisation](http://www.last.fm/api/desktopauth) but the [web authorisation](https://www.last.fm/api/webauth). The authantication is done by parsing the api key inside the url. This is done for you by the MMM-Scrobbler module. I'm sure this works fine part works fine because it does for me.

**Comment by PtrBld** [comment]
I think this is fixed. Thanks ganget!
